project:
  type: website

website:
  title: "E155 Portfolio"
  navbar:
    left:
      - text: Labs
        menu:
          - href: labs/lab1/lab1.qmd
            text: Lab 1
          - href: labs/lab2/lab2.qmd
            text: Lab 2
      - href: blog.qmd
        text: Blog

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
